### ISSUE TITLE
Simple Regression values are not close to Ordinary Least Square's values

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/DrivetrainCharacterization#1] opened 2019-01-27 21:01 UTC
The return values of simpleRegression() and ordinaryLeastSquares() do not match eachother. The problem most likely lies in ordinaryLeastSquares() and not in simpleRegression().

**Comment by brettle** [comment] 2019-01-28 05:55
The values shouldn't match exactly because simpleRegression() estimates the values separately while ordinaryLeastSquares() estimates the values together. How, different are they?

Also, I don't think left_velocities.size() ever be less than 2 when this line is reached:

https://github.com/DeepBlueRobotics/DrivetrainCharacterization/blob/50195587263780c5a994d5770978d1af910cf57e/DrivetrainCharacterization/src/DrivetrainCharacterization.java#L77

Lastly, didn't you decide that you needed a step size of ~30 to get the noise level in the acceleration down to a reasonable level.

**Comment by alexander-mcdowell** [comment] 2019-01-30 03:43
Even with a step size of thirty, the issue remains. With a step size of 1, the output of the script is:

`Velocity Constant is 9.853635739836905 and the Acceleration Constant is 0.4754123694760919 with a voltage intercept of 5.952596963319218E-4`

Whereas with a step size of 30, the output of the script is:

`Velocity Constant is 9.194657043378212 and the Acceleration Constant is 0.47905001061478936 with a voltage intercept of 0.00806956003180515`

So yes, while the result is becoming closer to the expected result (kV = 0.5117110889241047, kA = 0.3206685105499916), the difference between Simple Regression's kV and OLS's kV is considerable. Strangely, as the step size increases, kV tends to decrease whereas kA and voltage intercept seem to increase.

The problem must be that my implementation of OLS is incorrect. There might be some parameters that I didn't change or I might be misusing OLS's output. If this becomes more of a problem, it might be beneficial for us to accept the values of Simple Regression and move on.

**Comment by brettle** [comment] 2019-01-30 03:59
You didn't address my comment that I don't think left_velocities.size() ever be less than 2 when this line is reached:

https://github.com/DeepBlueRobotics/DrivetrainCharacterization/blob/50195587263780c5a994d5770978d1af910cf57e/DrivetrainCharacterization/src/DrivetrainCharacterization.java#L77

I suspect that is the source of your problem.

**Comment by alexander-mcdowell** [comment] 2019-01-30 04:23
When I changed the code to compute the acceleration with step size, I changed the code to the following:

`if (left_velocities.size() >= spread) {
                    	double a1 = (v1 - left_velocities.get(left_velocities.size() - spread)) / (spread * 0.02);
                        double a2 = (v2 - right_velocities.get(right_velocities.size() - spread)) / (spread * 0.02);
                        // System.out.println(a1 + "," + a2);
                        accelerations.add((Math.abs(a1) + Math.abs(a2)));
                    }`

The condition is necessary to prevent an index error (left_velocities.get(-19)). Even when I changed the condition, the result is still the same.

**Comment by brettle** [comment] 2019-01-30 04:24
Actually, that is only part of the problem. The bigger issue is that you are misinterpreting the regression parameters that are returned. The intercept is params[0], the kv is params[1], and ka is params[2].

The [OLSMultipleLinearRegression doc](https://commons.apache.org/proper/commons-math/javadocs/api-3.0/org/apache/commons/math3/stat/regression/OLSMultipleLinearRegression.html) says "When the model is estimated using an intercept term (i.e. when isNoIntercept is false as it is by default), the X matrix includes an **initial** column identically equal to 1." Basically, that means it is estimating the params for this model:
y = params[0]*1 + params[1]*x[0] + params[2]*x[1]
So, params[0] corresponds to the intercept term.

**Comment by brettle** [comment] 2019-01-30 04:28
Regardless of the spread, the original code (and probably your new code) was sometimes an acceleration based on two velocities that came from different files/experiments. Those accelerations are bogus and should not be used.

**Comment by alexander-mcdowell** [comment] 2019-01-30 04:29
The estimation is much more accurate now after changing the parameters. Here is the result with 30 spread:

`Velocity Constant is 0.47905001061478936 and the Acceleration Constant is 0.0968347203816618 with a voltage intercept of 0.7662214202815177`

Which is close to the previous values:

`Velocity Constant is 0.5117110889241047 and the Acceleration Constant is 0.3206685105499916 with a voltage intercept of 0.6587560409636033`

In fact, the acceleration constant is only 0.01 off from the value in the paper (0.1), however the velocity constant is off by 0.33 (the paper has a value of 0.81).

**Comment by alexander-mcdowell** [comment] 2019-01-30 04:32
The acceleration for file X is solely based on the velocities from file X - I am not merging both files.

**Comment by brettle** [comment] 2019-01-30 04:34
Commit and push so I can review. That was not true before.

--Dean

**Comment by brettle** [comment] 2019-01-30 05:02
Thanks for pushing. The first time line 76 is executed, what will the value of left_velocities.size() be?

**Comment by alexander-mcdowell** [comment] 2019-01-30 05:04
Left_velocities.size() = the step size value (in this case 30), as it should. To me, everything seems fine.

**Comment by alexander-mcdowell** [comment] 2019-01-30 05:05
No wait, sorry. That's wrong. I was looking at a previous line. The actual value on line 76 is 1069, not the step size. I will fix this now

**Comment by alexander-mcdowell** [comment] 2019-01-30 05:09
The new values with the changes are now:
`Velocity Constant is 0.4829227502002621 and the Acceleration Constant is 0.13037626144001221 with a voltage intercept of 0.7457497036387576`
I can push the changes now for review if necessary.

**Comment by brettle** [comment] 2019-01-30 05:11
Yes. Please push. Thanks!

**Comment by brettle** [comment] 2019-01-30 05:27
Getting warmer but the velocities and voltages you are removing on lines 100-104 are not the ones you should be removing.

**Comment by alexander-mcdowell** [comment] 2019-01-30 05:32
The newest fix changes the constants to:
`Velocity Constant is 0.4757063634438342 and the Acceleration Constant is 0.3028959310593429 with a voltage intercept of 0.5116430461071434`
compared to the regression estimate of:
`Velocity Constant is 0.5117110889241047 and the Acceleration Constant is 0.3206685105499916 with a voltage intercept of 0.6587560409636033`

I should be removing the values correctly now. I remove the values after every file pre-processing.

**Comment by brettle** [comment] 2019-01-30 05:34
Great! I think you can close this bug.

In general, you'd be better off (in terms of avoiding these kinds of errors and making the code shorter, and more readable) if you reorganized the code so you could do something like:
DataSet ds = parseCsv(file);
ds.addAcceleration(int spread);
ds.append(parseCsv(file2).addAcceleration(spread));
ds.computeParameters();

**Closed as completed** 2019-01-30 05:35 UTC

**Comment by alexander-mcdowell** [comment] 2019-01-30 05:36
Thanks for the help! I would have done a better job programming this but I had the idea that this was going to be a quick script. Needless to say, it was not.
